### ISSUE TITLE
calloc arguments "backwards"

### ISSUE THREAD

**Issue by keith-skinner** [arewhyaeenn/COMP_232_CI_LISP#23]
https://github.com/arewhyaeenn/CI_LISP/blob/master/src/ciLisp.c#L64

Also an awkward C99 way of saying:
```c
    AST_NODE *node = calloc(1, sizeof(AST_NODE));
    if (node == NULL) {
        yyerror("Memory allocation failed!");
        return NULL;
    }
```
> `void* calloc( size_t num, size_t size );`
> https://en.cppreference.com/w/c/memory/calloc

**Comment by arewhyaeenn** [comment]
While this is true, it is also inconsequential. I kind of like it, it provides a lighter "silly" quirk, which in turn provides an excuse to discuss calloc an extra time in class without it just being like "so here's what calloc does...."
