### ISSUE TITLE
Node doesn't exist

### ISSUE THREAD

**Issue by keith-skinner** [arewhyaeenn/COMP_232_CI_LISP#24]
https://github.com/arewhyaeenn/CI_LISP/blob/3e17b2a6da4fcd5eb7ff7792b850cd5a30234f07/src/ciLisp.c#L90

either make a default node at the top: `AST_NODE * node = NULL;`
or have the function: `return NULL;`

**Comment by arewhyaeenn** [comment]
Looks like you dealt with this one in your pull requests :)
