### ISSUE TITLE
No return value for function that returns

### ISSUE THREAD

**Issue by keith-skinner** [arewhyaeenn/COMP_232_CI_LISP#25]
https://github.com/arewhyaeenn/CI_LISP/blob/3e17b2a6da4fcd5eb7ff7792b850cd5a30234f07/src/ciLisp.c#L100

The function has a return value. Although C will default to saying "I guess you want this to return 0" it is still an odd error
`return NULL;` would fix this.

**Comment by arewhyaeenn** [comment]
Also handled in your pull requests 👍
