### ISSUE TITLE
Consider adding a DEFAULT_RET_VAL

### ISSUE THREAD

**Issue by keith-skinner** [arewhyaeenn/COMP_232_CI_LISP#26]
Something like:
```c
#define DEFAULT_RET_VAL {INT_TYPE, NAN}
```

**Comment by keith-skinner** [comment]
Could leave it in ciLisp.h or ciLisp.c

**Comment by arewhyaeenn** [comment]
This is actually already in the solution repository (with the exact same identifier); I'm not sure why I removed it when making the handout... huh. I've updated the handout. Thank you!
