### ISSUE TITLE
Possible memory leak each line.

### ISSUE THREAD

**Issue by keith-skinner** [arewhyaeenn/COMP_232_CI_LISP#27]
https://github.com/arewhyaeenn/CI_LISP/blob/3e17b2a6da4fcd5eb7ff7792b850cd5a30234f07/src/ciLisp.l#L127-L128

Is this causing a memory leak?
If so, either move the free expression inside the while loop or set the `s_expr_str` to null once outside the loop and set `s_expr_str_len` to 0 once outside the loop as well.

**Comment by arewhyaeenn** [comment]
You're right, this should be leaking. My solution doesn't leak, but my solution doesn't have those lines... 😅 Looks like I didn't update the handout with a couple changes I made at the end.

Thank you Keith!
